config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#LoginCreate
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#                      help GET    /help(.:format)                                                                          static_pages#help
#                     about GET    /about(.:format)                                                                         static_pages#about
#                   contact GET    /contact(.:format)                                                                       static_pages#contact
#                department GET    /department(.:format)                                                                    static_pages#department
#                   address GET    /address(.:format)                                                                       emp_details#address
#               emp_details GET    /emp_details(.:format)                                                                   emp_details#index
#                           POST   /emp_details(.:format)                                                                   emp_details#create
#            new_emp_detail GET    /emp_details/new(.:format)                                                               emp_details#new
#           edit_emp_detail GET    /emp_details/:id/edit(.:format)                                                          emp_details#edit
#                emp_detail GET    /emp_details/:id(.:format)                                                               emp_details#show
#                           PATCH  /emp_details/:id(.:format)                                                               emp_details#update
#                           PUT    /emp_details/:id(.:format)                                                               emp_details#update
#                           DELETE /emp_details/:id(.:format)                                                               emp_details#destroy
#        login_master_index GET    /login_master(.:format)                                                                  login_master#index
#                           POST   /login_master(.:format)                                                                  login_master#create
#          new_login_master GET    /login_master/new(.:format)                                                              login_master#new
#         edit_login_master GET    /login_master/:id/edit(.:format)                                                         login_master#edit
#              login_master GET    /login_master/:id(.:format)                                                              login_master#show
#                           PATCH  /login_master/:id(.:format)                                                              login_master#update
#                           PUT    /login_master/:id(.:format)                                                              login_master#update
#                           DELETE /login_master/:id(.:format)                                                              login_master#destroy
#                           GET    /auth/:provider/callback(.:format)                                                       sessions#create
#              auth_failure GET    /auth/failure(.:format)                                                                  redirect(301, /)
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  #resources :sessions
  get   '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#LoginCreate'
  delete '/logout',  to: 'sessions#destroy'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  #get  '/department', to: 'static_pages#department'
  get '/address', to: 'emp_details#address'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  

  resources :emp_details
  resources :login_master
  resources :emp_address
  resources :leave
  resources :department 
  resources :designation
  
  resources :salary


  #resources :sessions, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :bigint(8)        not null, primary key
#  Name       :string
#  Remark     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :integer
#

class Department < ApplicationRecord
	validates :Name,:Remark,presence: true
	has_many :designation
	enum status: {Active: 0, InActive: 1}
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
	include LoginMasterHelper
	def index
		@emp = LoginMaster.find(session[:user_id])
		@department = Department.all
	end

	def new
		@department = Department.new
	end

	def create
		@department = Department.new(department_params)
		#@emp = LoginMaster.find(session[:user_id])
		if @department.save
			redirect_to department_index_path
		else
			#redirect_to new_department_path
			respond_to do |f|
				f.js
				@department.errors.any?
				@department.errors.full_messages.each do |m|
				end
			end
		end
	end
	

	def edit
  	@department = Department.find(params[:id])
  end

 	def update
 		@department = Department.find(params[:id])
 		@department.update_attributes!(department_params)
	 	redirect_to department_index_path
 	end

	def show
		#@emp1 = EmpMaster.where(login_master_id: params[:id])	
		@department=Department.find(params[:id])
	end

	def destroy
		@department = Department.find(params[:id])
		@department.status = 1
		@department.save

		respond_to do |f|
	 		f.html{redirect_to department_index_path}
	 		f.js
	 	end
	end

	private
		def department_params
			params.require(:department).permit(:Name,:Remark)
		end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/views/department/_department.html.erb
<div class="container", id="department_details">
	<table class="table table-bordered" >
		<thead>
			<tr>
				<th>No.</th>
				<th>Name</th>
				<th>Remark</th>
				<th>Status</th>
				<th colspan="3"><center>Actions</center></th>
			</tr>
		</thead>
	  <tbody class="dept_details">
	  		<% no = 0 %>
				<% @department.each do |d| %>
					<tr id="@department.id">
						<td><%= no+= 1 %></td>
						<td><%= d.Name %><%#= link_to d.Name , designation_path(d.id) %></td>
						<td><%= d.Remark%></td>
						<td><%= d.status%></td>
						<td><%= link_to "Show", department_path(d.id), remote: true %></td>
						<% if check_admin %>
						<td><%= link_to "Edit",  edit_department_path(d.id), remote: true %></td>
						<td><%= link_to "Delete", department_path(d.id), method: :delete,
						data: {confirm: 'Are You Sure?'},remote: true , 
						:class => "delete_dept"%></td>
						<% end %>
					</tr>
				<% end %>
		</tbody>
	</table>
</div>

app/views/department/_edit.html.erb
<h3><%= "Editing #{@department.Name}" %></h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_for(@department,remote: true, html: { style: "display:inline;" }) do |f| %>
      <%= f.label :Name %>
      <%= f.text_field :Name, class: 'form-control' %>
      <br>
      <%= f.label :Remark %>
      <%= f.text_area :Remark, size:'50*10', class: 'form-control' %>
      <br>
      
      <%= f.submit "Apply", class: "btn btn-primary" %>  | 
      <%= link_to "Cancel", " ", class: "btn btn-primary", data: {dismiss: "modal"} %>    
      <% end %>
  </div>
</div>

app/views/department/_index.html.erb
<h2 class="header">Welcome</h2>
<% if @emp.role == "Admin" %>
	<%= link_to "Add New Department", new_department_path ,id: "new_link",remote: true%>
	<%= render 'department' %>
<% else %>
	<%= render 'department' %>
<% end %>

	

app/views/department/_new.html.erb
<h2 class="header1">Add Department</h2>
<div class="row",id="new_department">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_for(@department,url: department_index_path,remote: true ) do |f| %>
      
      <span id="helpBlock" class="help-block"></span>

      <%= f.label :Name %>
      <%= f.text_field :Name, class: 'form-control' %>
      <br>
      <%= f.label :Remark %>
      <%= f.text_area :Remark, size:'50*10', class: 'form-control' %>
      <br>
      
      <%= f.submit "Apply", class: "btn btn-primary" %>   |  
      <%= link_to "cancel", " ", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/department/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	  <div class="modal-header" >
			<h2><%= @department.Name %> Department is <%= @department.status%></h2>
			<h3>Remark : </h3><%= @department.Remark %> | 
			<%= link_to "back", department_index_path %>
		</div>
	</div>
</div>

app/views/department/create.js.erb
var errors = ""
<% if @department.errors.any? %>
	<% @department.errors.full_messages.each do |m| %>
		errors += "<div class='notice alert-danger'><%= escape_javascript(m)%></div>" 
		<% end %>	
		$("#helpBlock").html(errors);
<% else %>
	$(".header1").hide();
	$(".header").show()
	$("#new_link").show()
	$("#new_department").hide().after("<%= j render 'index'%>");
	$("#department_details_path").show();
// $("#department_details").show();
<% end %>

app/views/department/destroy.js.erb
// var deleted_row = "#department-<%= @department.id %>";
// $(deleted_row).remove();
// $("#department_details").load("#department_details");
// $("#edit_department_<%= @department.id %>").remove();
// $("#department_details").fadeOut();

// $("#edit_department_<%= @department.id %>").fadeOut(function() {
//   return $(this).remove().draw();
// });
$('.delete_dept').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/department/edit.html.erb
<%= render 'edit' %>
		

app/views/department/edit.js.erb
// $("#department-modal").html("<%= escape_javascript(render 'edit') %>")
// $("#department-modal").modal("show")
// $("#department_details").hide().after("<%= j render 'edit' %>")

$(".header").hide();
$("#new_link").hide();
$("#department_details").hide().after("<%= j render 'edit' %>")

app/views/department/index.html.erb
<%= render 'index' %>

<div id="department-modal" class="modal fade"></div>

app/views/department/new.html.erb
<%= render 'new' %>

app/views/department/new.js.erb
$(".header").hide()
$("#new_link").hide().after("<%= j render ('new') %>");
$("#department_index_path").remove();
$("#department_details").hide();
$("#product-modal").html("<%= escape_javascript(render 'new') %>")
$("#product-modal").modal("show")

app/views/department/show.html.erb
<%= render 'show' %>

app/views/department/show.js.erb
// $("#product-modal").html("<%= escape_javascript(render 'show') %>")
// $("#product-modal").modal("show")

$("#department-modal").html("<%= escape_javascript(render 'show' )%>");
$("#department-modal").modal("show");