config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#LoginCreate
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#                      help GET    /help(.:format)                                                                          static_pages#help
#                     about GET    /about(.:format)                                                                         static_pages#about
#                   contact GET    /contact(.:format)                                                                       static_pages#contact
#                department GET    /department(.:format)                                                                    static_pages#department
#                   address GET    /address(.:format)                                                                       emp_details#address
#               emp_details GET    /emp_details(.:format)                                                                   emp_details#index
#                           POST   /emp_details(.:format)                                                                   emp_details#create
#            new_emp_detail GET    /emp_details/new(.:format)                                                               emp_details#new
#           edit_emp_detail GET    /emp_details/:id/edit(.:format)                                                          emp_details#edit
#                emp_detail GET    /emp_details/:id(.:format)                                                               emp_details#show
#                           PATCH  /emp_details/:id(.:format)                                                               emp_details#update
#                           PUT    /emp_details/:id(.:format)                                                               emp_details#update
#                           DELETE /emp_details/:id(.:format)                                                               emp_details#destroy
#        login_master_index GET    /login_master(.:format)                                                                  login_master#index
#                           POST   /login_master(.:format)                                                                  login_master#create
#          new_login_master GET    /login_master/new(.:format)                                                              login_master#new
#         edit_login_master GET    /login_master/:id/edit(.:format)                                                         login_master#edit
#              login_master GET    /login_master/:id(.:format)                                                              login_master#show
#                           PATCH  /login_master/:id(.:format)                                                              login_master#update
#                           PUT    /login_master/:id(.:format)                                                              login_master#update
#                           DELETE /login_master/:id(.:format)                                                              login_master#destroy
#                           GET    /auth/:provider/callback(.:format)                                                       sessions#create
#              auth_failure GET    /auth/failure(.:format)                                                                  redirect(301, /)
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  #resources :sessions
  get   '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#LoginCreate'
  delete '/logout',  to: 'sessions#destroy'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  #get  '/department', to: 'static_pages#department'
  get '/address', to: 'emp_details#address'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  

  resources :emp_details
  resources :login_master
  resources :emp_address
  resources :leave
  resources :department 
  resources :designation
  
  resources :salary


  #resources :sessions, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/salary.rb
# == Schema Information
#
# Table name: salaries
#
#  id             :bigint(8)        not null, primary key
#  Date_Of_Salary :date
#  Amount         :decimal(, )
#  emp_master_id  :bigint(8)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  status         :integer          default(0)
#

class Salary < ApplicationRecord
  belongs_to :emp_master
  validates :Date_Of_Salary,presence: true
  validates :Amount,presence: true, numericality: true
end

app/controllers/salary_controller.rb
class SalaryController < ApplicationController
	include LoginMasterHelper
	def index 
		#@salary = Salary.all
		@emp1 = LoginMaster.find(session[:user_id])
		@emp = EmpMaster.all
	end

	def new
		@salary = Salary.new
		#@s = LoginMaster.find(session[:user_id])
		#binding.pry
		#@emp = EmpMaster.where(login_master_id: @s.id)
		#binding.pry
	end

	def create
		@salary = Salary.new(salary_params)
		if @salary.save
			redirect_to salary_index_path
		else
			#redirect_to new_salary_path
			respond_to do |f|
				f.js
				@salary.errors.any?
				@salary.errors.full_messages.each do |m|
				end
			end
		end
	end

	def show
		@salary = Salary.where(emp_master_id: params[:id])
	end


	def edit
		@salary = Salary.find(params[:id])
	end

	
	def update
		@salary = Salary.find(params[:id])
		@salary.update_attributes!(salary_params)
		redirect_to salary_index_path
	end

	def destroy
		@salary = Salary.find(params[:id])
		@salary.destroy
		redirect_to salary_index_path
	end

	private
		def salary_params
			params.require(:salary).permit(:Date_Of_Salary,:Amount,:emp_master_id)
		end
end

app/helpers/salary_helper.rb
module SalaryHelper
	def empty
		Salary.where(emp_master_id: params[:id]).empty?
	end
end

app/views/salary/_edit.html.erb
<h2>Edit salary details</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <% @emp_master = Salary.find(params[:id]) %>
    <%= form_for(@salary,url: salary_path(params[:id]), remote: true) do |f| %>
      <%= f.label :Date_Of_Salary %>
      <%= f.date_field :Date_Of_Salary, class: 'form-control' %>
      <br>
      <%= f.label :Amount %>
      <%= f.number_field :Amount, class: 'form-control' %>
      <br>
      <%= f.hidden_field :emp_master_id, value: @emp_master.emp_master_id %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>   |  
      <%= link_to "Cancel", " ", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/salary/_index.html.erb
<% no = 0	 %>	
<% @emp.each do |e| %>
 		<tr>
			<td><%= no+= 1 %></td>
			<td><%= e.Username%></td>
			<td><%= e.Email	%></td>
			<td><%= link_to "Show", salary_path(id: e.id), remote: true %></td>
		</tr>
<% end %>

app/views/salary/_new.html.erb
<h2>Add Salary : </h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_for(@salary,url: salary_index_path, remote: true ) do |f| %>

      <span id="helpBlock" class="help-block"></span>

      <%= f.label :Date_Of_Salary %>
      <%= f.date_field :Date_Of_Salary, class: 'form-control' %>
      <br>
      <%= f.label :Amount %>
      <%= f.number_field :Amount, class: 'form-control' %>
      <br>
      <%= f.hidden_field :emp_master_id, value: params[:id] %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>   |  
      <%= link_to "cancel", " ", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/salary/_show.html.erb
<div id="show_salary">
	<h2>Salary Details</h2>
	<% if check_admin %>
		<% if @salary.exists? %> 
			<td><%=link_to "Edit Salary Details",edit_salary_path(@salary.ids), remote: true%></td>	 |
			<td><%=link_to "Delete Salary Details",salary_path(@salary.ids),method: :delete,data: {confirm: "Are You Sure?"}, remote: true %></td>	
		<% else %>
			<td><%=link_to "Add Salary Details" , new_salary_path(id: params[:id]) , remote: true%>
			</td>
		<% end %>  |  
	<% end %>
	<%= link_to "Back", " " %> 

	<% @salary.each do |s| %>
		<h3>Date : </h3><%= s.Date_Of_Salary %>
		<br>
		<h3>Amount : </h3><%= s.Amount %>
		<br>
		<br>
	<% end %>
</div>

app/views/salary/create.js.erb
var errors = ""
<% if @salary.errors.any? %>
	<% @salary.errors.full_messages.each do |m| %>
		errors += "<div class='notice alert-danger'><%= escape_javascript(m)%></div>" 
		<% end %>	
		$("#helpBlock").html(errors);
<% else %>
$(".salary_details").html("<%= escape_javascript(render 'index') %>")
<% end %>

app/views/salary/destroy.js.erb
$("<%=j render 'show' %>");

app/views/salary/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <% @emp_master = Salary.find(params[:id]) %>
    <%= form_for(@salary,url: salary_path(params[:id])) do |f| %>
      <%= f.label :Date_Of_Salary %>
      <%= f.date_field :Date_Of_Salary, class: 'form-control' %>
      <br>
      <%= f.label :Amount %>
      <%= f.number_field :Amount, class: 'form-control' %>
      <br>
      <%= f.hidden_field :emp_master_id, value: @emp_master.emp_master_id %>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/salary/edit.js.erb
$("#show_salary").hide().after("<%= j render 'edit' %>")

app/views/salary/index.html.erb
<h2 class="header">index page of salary</h2>
<%# if check_admin %>
<div class="container" id="salary_index">
	<table class="table table-bordered" >
		<thead>
			<tr>
				<th>No.</th>
				<th>Employee UserName</th>
				<th>Employee Email</th>
				<th colspan="2"><center>Actions</center></th>
			</tr>
		</thead>
    <tbody class="salary_details">
			<%= render 'index' %>	
	</tbody>
	</table>
</div>
<%# end %>

app/views/salary/new.html.erb
<%= render 'new' %>

app/views/salary/new.js.erb
$("#show_salary").remove();
$("#salary_index").hide().after("<%=  j render 'new' %>")

app/views/salary/show.js.erb
$(".header").remove();
$(".new_link").remove();
$("#salary_index").hide().after("<%= j render 'show' %>" );