config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     login GET    /login(.:format)                                                                         sessions#new
#                           POST   /login(.:format)                                                                         sessions#LoginCreate
#                    logout DELETE /logout(.:format)                                                                        sessions#destroy
#                      help GET    /help(.:format)                                                                          static_pages#help
#                     about GET    /about(.:format)                                                                         static_pages#about
#                   contact GET    /contact(.:format)                                                                       static_pages#contact
#                department GET    /department(.:format)                                                                    static_pages#department
#                   address GET    /address(.:format)                                                                       emp_details#address
#               emp_details GET    /emp_details(.:format)                                                                   emp_details#index
#                           POST   /emp_details(.:format)                                                                   emp_details#create
#            new_emp_detail GET    /emp_details/new(.:format)                                                               emp_details#new
#           edit_emp_detail GET    /emp_details/:id/edit(.:format)                                                          emp_details#edit
#                emp_detail GET    /emp_details/:id(.:format)                                                               emp_details#show
#                           PATCH  /emp_details/:id(.:format)                                                               emp_details#update
#                           PUT    /emp_details/:id(.:format)                                                               emp_details#update
#                           DELETE /emp_details/:id(.:format)                                                               emp_details#destroy
#        login_master_index GET    /login_master(.:format)                                                                  login_master#index
#                           POST   /login_master(.:format)                                                                  login_master#create
#          new_login_master GET    /login_master/new(.:format)                                                              login_master#new
#         edit_login_master GET    /login_master/:id/edit(.:format)                                                         login_master#edit
#              login_master GET    /login_master/:id(.:format)                                                              login_master#show
#                           PATCH  /login_master/:id(.:format)                                                              login_master#update
#                           PUT    /login_master/:id(.:format)                                                              login_master#update
#                           DELETE /login_master/:id(.:format)                                                              login_master#destroy
#                           GET    /auth/:provider/callback(.:format)                                                       sessions#create
#              auth_failure GET    /auth/failure(.:format)                                                                  redirect(301, /)
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  #resources :sessions
  get   '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#LoginCreate'
  delete '/logout',  to: 'sessions#destroy'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  #get  '/department', to: 'static_pages#department'
  get '/address', to: 'emp_details#address'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  

  resources :emp_details
  resources :login_master
  resources :emp_address
  resources :leave
  resources :department 
  resources :designation
  
  resources :salary


  #resources :sessions, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/designation.rb
# == Schema Information
#
# Table name: designations
#
#  id            :bigint(8)        not null, primary key
#  post          :string
#  department_id :bigint(8)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  status        :integer          default(0)
#

class Designation < ApplicationRecord
  belongs_to :department
  validates :post, presence: true, length: {maximum: 50}
end

app/controllers/designation_controller.rb
class DesignationController < ApplicationController
	include LoginMasterHelper
	def index
		@designation = Designation.all
	end

	def new		
		@designation = Designation.new

	end

	def create
		@designation = Designation.new(designation_params)
		if @designation.save
			redirect_to designation_index_path
		else
			#redirect_to new_designation_path
			respond_to do |f|
				f.js
				@designation.errors.any?
				@designation.errors.full_messages.each do |m|
				end
			end
		end
	end

	def show

		@designation = Designation.find(params[:id])
		#binding.pry

		# @department = Department.find(params[:id])
		# #binding.pry
		# #if Designation.exists?(department_id: params[:id])
		# @designation = Designation.where(department_id: @department.id)
		#else
		#	redirect_to new_designation_path
		#@designation = Designation.find(@designation1.ids)
		#binding.pry
		#end
	end

	def edit
		@designation = Designation.find(params[:id])
		
	end

	def update
		@designation = Designation.find(params[:id])
		@designation.update_attributes!(designation_params)
		redirect_to designation_index_path
	end

	def destroy
		@designation = Designation.find(params[:id])	
		
		@designation.destroy
		redirect_to designation_index_path
	end

	private
		def designation_params
			params.require(:designation).permit(:post,:department_id)
		end
end

app/helpers/designation_helper.rb
module DesignationHelper
end

app/views/designation/_edit.html.erb
<h2 class="header1">Edit <%= @designation.post %></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_for(@designation, url: designation_path(params[:id]), remote: true)	do |f| %>
      <%= f.label :Post %>
      <%= f.text_field :post, class: 'form-control' %>
       <br>
      <%= f.collection_select :department_id,Department.all,:id, :Name %>
      <br>
      <br>
      <%#= f.hidden_field :department_id, value: params[:id] %>
      <%= f.submit "Add", class: "btn btn-primary" %>  |  
      <%= link_to "Cancel", " ", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/designation/_index.html.erb
<% no = 0	%>
<% @designation.each do |d| %>
<tr id="designation_new">
	<td><%= no+= 1 %></td>
	<td><%= d.post %></td>
	<td><%= link_to "Show", designation_path(d.id), remote: true %></td>
	<% if check_admin %>
		<td><%= link_to "Edit",  edit_designation_path(d.id), remote: true %></td>
		<td><%= link_to "Delete", designation_path(d.id), method: :delete, data: {confirm: "Are You Sure?"},remote: true %></td>
	<% end %>
<% end %>
</tr>

app/views/designation/_new.html.erb
<h2 class="header2">Add new Designation:</h2>
<div class="row" id="designation_new">
  <div class="col-md-6 col-md-offset-3" >
    <%= form_for(@designation, url: designation_index_path, remote: true)	do |f| %>
      
      <span id="helpBlock" class="help-block"></span>
      
      <%= f.label :Post %>
      <%= f.text_field :post, class: 'form-control' %>
      <br>
      <%= f.collection_select :department_id,Department.all,:id, :Name %>
      <br>
      <br>
      <%#= f.hidden_field :department_id, value: params[:id] %>
      <%= f.submit "Add", class: "btn btn-primary" %>  |  
      <%= link_to "Cancel", " ", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>	

app/views/designation/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
	  <div class="modal-header" >
		  	<h2><%= @designation.post %></h2>
				<%= link_to "back", " " %>
		</div>
	</div>
</div>

app/views/designation/create.js.erb
var errors = ""
<% if @designation.errors.any? %>
	<% @designation.errors.full_messages.each do |m| %>
		errors += "<div class='notice alert-danger'><%= escape_javascript(m)%></div>" 
		<% end %>	
		$("#helpBlock").html(errors);
<% else %>
	$(".header2").show();
	$(".new_link").show();
	$("#designation_new").hide().after("<%= j render 'index' %>");
<% end %>

app/views/designation/destroy.js.erb
$('.delete_dept').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/designation/edit.js.erb
$(".header1").hide();
$(".new_link").hide();
$("#designation_index").hide().after("<%= j render 'edit' %>")

app/views/designation/index.html.erb
<h2 class="header1">All Posts </h2>
<%= link_to "Add new Designation", new_designation_path,remote: true, :class=>"new_link"%>
<div class="container" id="designation_index">
	<table class="table table-bordered" >
		<thead>
			<tr>
				<th>No.</th>
				<th>Post</th>
				<th colspan="3"><center>Actions</center></th>
			</tr>
		</thead>
	  <tbody>
			<%= render 'index' %>
		</tbody>
	</table>
</div>

app/views/designation/new.html.erb
<%= render 'new' %>

app/views/designation/new.js.erb
$(".header1").hide();
$(".new_link").hide();
$("#designation_index").hide().after("<%= j render 'new' %>");

app/views/designation/show.js.erb
$(".header1").hide();
$(".new_link").hide();
$("#designation_index").hide().after("<%= j render 'show' %>");